# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    loaders:
        default:
            filesystem:
                locator: filesystem_insecure
                
                    
    # valid drivers options include "gd" or "gmagick" or "imagick"
    filter_sets:
        my_background_filter:
            quality: 50
            filters:
                watermark_image:

                    # path to the watermark file (prepended with "%kernel.project_dir%")
                    image: public\assets\copyright.png

                    # size of the water mark relative to the input image
                    size: 0.050

                    # set the position of the watermark
                    position: bottomleft               
        # name our filter set "my_watermark_filter"
        # my_watermark_filter:
        #     filters:

        #         # use and setup the "watermark_image" filter
        #         watermark_image:

        #             # path to the watermark file (prepended with "%kernel.project_dir%")
        #             image: uploads/PromoHP4-MimiGeignarde-60f680e59c221.jpg

        #             # size of the water mark relative to the input image
        #             size: 30

        #             # set the position of the watermark
        #             position: center