# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    loaders:
        default:
            filesystem:
                locator: filesystem_insecure
                
                    
    # valid drivers options include "gd" or "gmagick" or "imagick"
    filter_sets:
        # nom du filtre
        my_background_filter:
            # réduit de 50% la qualité de l'image
            quality: 50
            filters:
                watermark_image:
                    # path de l'image du copyright
                    image: public\assets\copyright.png
                    # taille de l'image
                    size: 0.050
                    #position
                    position: bottomleft               
        # name our filter set "my_watermark_filter"
        # my_watermark_filter:
        #     filters:

        #         # use and setup the "watermark_image" filter
        #         watermark_image:

        #             # path to the watermark file (prepended with "%kernel.project_dir%")
        #             image: uploads/PromoHP4-MimiGeignarde-60f680e59c221.jpg

        #             # size of the water mark relative to the input image
        #             size: 30

        #             # set the position of the watermark
        #             position: center