security:
    encoders:
            App\Entity\Player:
                algorithm: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\Player
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users_in_memory
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            logout:
                path: app_logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    # enable_authenticator_manager: true
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    #Todo creation des roles utilisateur
    access_control:
        - { path: ^/question, roles: ROLE_ADMIN }
        - { path: ^/answer, roles: ROLE_ADMIN }
    
    role_hierarchy:
        #ROLE_ADMIN: ROLE_USER
